spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///pethome
    username: root
    password: 123456

mybatis:
  mapper-locations: cn/itsource/*/mapper/*Mapper.xml

server:
  port: 80

logging:
  level:
    cn:
     itsource: trace

